apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-rca
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./
    repoURL: https://github.com/jyotsanaarora/ArgoNamespace/test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=background
